### PR TITLE
Adapt to LAGUNA changes

### PR DESCRIPTION
**Pull request by fingolfin**
See https://github.com/gap-packages/laguna/pull/27

CC @alex-konovalov

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@fingolfin hmm, what are those problems in stable branches?

**Comment by fingolfin** [comment]
Huh, weird... no idea right now. Gotta investigate...

**Comment by olexandr-konovalov** [comment]
Starts with
```
#I  UnitLib package is not available. To see further details, enter
#I  SetInfoLevel(InfoPackageLoading,4); and try to load the package again.
```
but why?

**Comment by olexandr-konovalov** [comment]
@fingolfin of course, it asks LAGUNA 3.9.4 from Feb 2022. What to do?
a) don't test with GAP 4.10
b) how soon 3.9.4 will appear for GAP 4.11 ?

**Comment by fingolfin** [comment]
Not sure what you mean with "how soon 3.9.4 will appear for GAP 4.11".

Perhaps: "when will the GAP 4.11 branch be switched to using the new package distribution" ? That's a good question, I guess. I could do that right now.

**Comment by olexandr-konovalov** [comment]
Yes, exactly what I had in mind. Sometimes I write too short always counting on your abilities to read my mind :)

**Comment by fingolfin** [comment]
Updating the package distro for 4.11 is done in https://github.com/gap-system/gap/pull/4845 which needs to be approved by someone... :-)

**Comment by olexandr-konovalov** [comment]
@fingolfin so, after https://github.com/gap-system/gap/pull/4845 merged, can we re-run this PR's CI to check that it works?

**Comment by fingolfin** [comment]
Done. The 4.11 tests pass now. The 4.10 ones still fail. I guess should just require GAP >= 4.11

**Comment by olexandr-konovalov** [comment]
@fingolfin ok, happy go require 4.11, thanks!

**Pull request merged**
