### PR TITLE
gzip files are supported in Windows with GAP >= 4.10

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
This needs further adjustment. I've tried it on Windows in GAP 4.11.0, and it complains that 'gunzip' is not recognised. Indeed, just below the block you've removed we have
```
  gzfile := Concatenation( 
               GAPInfo.PackagesInfo.("unitlib")[1].InstallationPath,
               "/data/128/", filename, ".g.gz" );
  libfile := Filename( DirectoryTemporary(), "filename");
  Exec( Concatenation( "gunzip -c ", gzfile, " > ", libfile ) );
```
what now could be made in a better way.

**Comment by fingolfin** [comment]
Indeed, the whole extraction code ought to be simplified or even removed. Good to have CI tests again

**Comment by fingolfin** [comment]
Updated

**Review by olexandr-konovalov — CHANGES_REQUESTED** [review]
Thanks - you need also to remove the `if` clause with
```
Exec( Concatenation("rm ", libfile ) );
```
some lines below.

**Comment by fingolfin** [comment]
Argh! OK, updated once again

**Comment by olexandr-konovalov** [comment]
Dealing with the legacy code is hard... even when it's your own code...

**Review by olexandr-konovalov — APPROVED** [review]

**Comment by olexandr-konovalov** [comment]
@fingolfin Aargh the limitation for order 128 it's also in README and perhaps in the documentation! I will deal with it myself.

**Comment by fingolfin** [comment]
Sorry - I should habe grepped for 128! :-(

**Pull request merged**
