### PR TITLE
Remove lib/buildman.g

### LINKED ISSUE #13: Remove buildman.g
This is now obsolete - replaced by makedoc.g script.

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #13

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@fingolfin looks ok, but why CI was skipped?

**Comment by fingolfin** [comment]
No idea. Had the same issue with another PR here. Also the names of the checks are weird, and there are too few -- it seems the build matrix is not treated as a matrix

**Comment by olexandr-konovalov** [comment]
And restarting them did not work... Anyway, seems harmless PR, will merge and see if tests will be triggered in the master branch.

**Comment by olexandr-konovalov** [comment]
... and they do

**Pull request merged**
